import { HeaderMobile } from "@/src/widgets/headers";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["cyrillic", "latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full antialiased`}>
        <div className="mx-auto flex h-full w-[20.5rem] flex-col">
          <HeaderMobile />
          {children}
        </div>
      </body>
    </html>
  );
}
