import { Header } from "@/src/widgets/headers";
import { FooterMobile } from "@/src/widgets/footers";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["cyrillic", "latin"],
});

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" className="h-full text-[16px] xl:text-[16px]">
      <body className={`${inter.className} h-full antialiased`}>
        <div className="mx-auto h-full w-[91.1112vw] lg:w-[62.5vw] desktop:w-[66.667vw]">
          <Header />
          {children}
          <FooterMobile />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
